baseURL = "https://www.uranari.io/"
languageCode = "ja"
title = "uranari dayo"
theme = "nofancy"
canonifyurls = true

[params]
  description = "旅と写真とtech"

[author]
  name = "uranari"
  gaID = "UA-92817018-1"
  twitter = "@uranariz"